### ISSUE TITLE
The newly generated cat, clicking the 【Sell】 button results in an error: undefined is not an object

### ISSUE THREAD

**Issue by aibbones** [Schrodinger-AI/interface#272]
### Description
The newly generated cat, clicking the 【Sell】 button results in an error: undefined is not an object

### Steps To Reproduce
1. Enter the TG bot, generate a 9th generation cat
2. On the details page of the newly generated 9th generation cat, click the 【Sell】 button

### Current Behavior
- Error: undefined is not an object

### Expected Behavior
- No error

### Environment
- Platform: TG bot
![image](https://github.com/user-attachments/assets/2f584259-f66c-4355-9eda-6a4ef54a5343)
![image](https://github.com/user-attachments/assets/cbf07455-663c-4315-a21e-46f2451ffcbf)

**Comment by hugetttt** [comment]
It is caused by the delay in chain scanning.
