### ISSUE TITLE
The details page of the 9th generation cat, when others have listed it and the user does not own it, the Trade button is not displayed

### ISSUE THREAD

**Issue by aibbones** [Schrodinger-AI/interface#277]
### Description
The details page of the 9th generation cat, when others have listed it and the user does not own it, the Trade button is not displayed

### Steps To Reproduce
1. Entered the TDVW-SGR-151 details page, checked the display status of the Trade button

### Current Behavior
- The Trade button is not displayed

### Expected Behavior
- The Trade button should be displayed

### Environment
- Platform: TG bot
![image](https://github.com/user-attachments/assets/dae9def6-0781-4a41-b6fd-c4176c43da3c)
![image](https://github.com/user-attachments/assets/56cb9956-dfe8-4310-a0d9-9a2d6762298f)

**Comment by hugetttt** [comment]
The buy button is displayed only when the availableQuantity field of the nft-for-sale interface is greater than 1.
